Vagrant::Config.run do |config|
  config.vm.box = "ubuntu-1204-i386"
  config.vm.box_url = "http://vagrant.sensuapp.org/ubuntu-1204-i386.box"

  config.vm.customize [
    "modifyvm", :id,
    "--name", "Pressinator",
    "--memory", "1024"
  ]

  config.vm.provision :shell, :inline => "gem install chef -v 0.10.8 --no-rdoc --no-ri"

  config.vm.forward_port 21, 2121
  config.vm.forward_port 80, 8080

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.data_bags_path = "data_bags"
    chef.roles_path = "roles"
    chef.add_role("vagrant")
  end
end
